### ISSUE TITLE
ros2_crtk_python_client not available

### ISSUE THREAD

**Issue by liushuya7** [jhu-saw/sawNDITrackerROS2#2]
Hi @adeguet1,

The [crtk/crtk_python_client](https://github.com/jhu-saw/sawNDITrackerROS2/blob/56ae2464c42e524b4ee03c560ce8b07b2227d8d7/ndi_tracker.repos#L34) seems not available.
```
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

**Comment by liushuya7** [comment]
I found **[crtk_python_client](https://github.com/collaborative-robotics/crtk_python_client)** but not **ros2_crtk_python_client**. Are they the same?

**Comment by adeguet1** [comment]
My bad, I accidentally created that repository as private and it seems you're the first user...  The repository is now public.
